build:
  maxIssues: 100
  excludeCorrectable: true

config:
  validation: true
  warningsAsErrors: false

processors:
  active: false

console-reports:
  active: true

output-reports:
  active: true

complexity:
  LongMethod:
    active: true
    threshold: 60
    excludes: '**/test/**,**/androidTest/**,**/commonTest/**,**/jvmTest/**,**/jsTest/**,**/iosTest/**'
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
  NestedBlockDepth:
    active: true
    threshold: 5
  TooManyFunctions:
    active: true
    thresholdInFiles: 120
    thresholdInClasses: 80
    thresholdInInterfaces: 20
    excludes: '**/test/**,**/androidTest/**,**/commonTest/**,**/jvmTest/**,**/jsTest/**,**/iosTest/**'

coroutines:
  active: true
  SleepInsteadOfDelay:
    active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    excludes: '**/test/**,**/androidTest/**'

formatting:
  active: true
  autoCorrect: false
  Indentation:
    indentSize: 4
  ImportOrdering:
    layout: '*,java.**,javax.**,kotlin.**,^'
  NoWildcardImports:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
  PackageNaming:
    active: true

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  ForbiddenComment:
    comments: ['TODO', 'FIXME']
    allowedPatterns: '([A-Z]+-[0-9]+)'
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '100']
    ignoreEnums: true
    ignoreProperties: true
    ignoreAnnotation: true
    ignoreCompanionObjectPropertyDeclaration: true
  ReturnCount:
    max: 3
    excludeGuardClauses: true
  TrailingWhitespace:
    active: false
  NewLineAtEndOfFile:
    active: false
  LibraryEntitiesShouldNotBePublic:
    active: false